services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:keycloak-custom}
      POSTGRES_USER: ${POSTGRES_USER:keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:keycloak} -d ${POSTGRES_DB:keycloak-custom}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    build:
      context: .
    container_name: keycloak
    command: ["--optimized", "--import-realm"]
    environment:
      # set hostname if you are behind a reverse proxy
      # KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:keycloak-custom}
      KC_DB_USERNAME: ${POSTGRES_USER:keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:password}
      # Set default values for admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: adminpassword
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - keycloak-network

volumes:
  postgres_data:

networks:
  keycloak-network: {}